name: P-Bit BE Build Deployment Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "powarsteam" --password-stdin

      - name: Build Docker Image
        run: docker build -t powarsteam/pbit-be:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push powarsteam/pbit-be:latest

  deploy-to-dev:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    needs: build-image  # depends on the previous job finishing successfully

    steps:
      - name: SSH into Linode and deploy Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 172.233.114.136
          username: powarsteam
          key: ${{ secrets.SSH_KEY }}
          port: 5823
          script: |
            echo "Deploying P-Bit backend..."

            # Stop and remove any old containers if they exist
            docker stop pbit-be || true
            docker rm pbit-be || true

            # Clean up unused images
            docker image prune -f || true

            # Pull the latest image from Docker Hub
            docker pull powarsteam/pbit-be:latest

            # Run the new container
            docker run -d \
              --name pbit-be \
              --restart always \
              -p 8000:8000 \
              -e DB_HOSTNAME="a375161-akamai-prod-6782576-default.g2a.akamaidb.net" \
              -e DB_USER="akmadmin" \
              -e DB_PASSWORD="AVNS_aVitjiCj-ec-Wl2fDHL" \
              -e DB_PORT="19980" \
              -e DB_DATABASE="defaultdb" \
              -e JWT_SECRET_KEY="650FX$IyZT/XWn>£2/nL£PR?=%N" \
              -e JWT_ALGORITHM="HS256" \
              -e ACCESS_TOKEN_EXPIRE_MINUTES="30" \
              powarsteam/pbit-be:latest

            echo "✅ Deployment completed successfully!"
